###
# This is the place to override the opsworks_appsapi cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_appsapi/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Tomcat threadpool max size:
#
#normal['opsworks_appsapi']['tomcat']['threadpool_max_threads'] = 150
